CREATE TABLE job_config (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           job_name VARCHAR(255),
                           cron VARCHAR(255),
                           my_variable VARCHAR(255)
);